### ISSUE TITLE
Utils Module is not included in Index

### ISSUE THREAD

**Issue by copperwall** [woodruffw/muzak#1]
If `albums_by` or `songs_by` tries to throw an error, Muzak will die because `error` is not defined.

Also, when an `albums-by-artist` command is given with a non-existent artist, `albums_by` returns an array, which then gets `.keys` called on it by `albums_by_artists`, which causes Muzak to die.

```
zolokar at sabre in ~/muzak ruby -Ilib muzak.rb --debug --verbose
[debug] muzak is starting...
[verbose] loading config from /home/zolokar/.config/muzak/muzak.yml
[debug] loading index from /home/zolokar/.config/muzak/index.yml
loading Muzak::Plugin::StubPlugin
loading Muzak::Plugin::Notify
loading Muzak::Plugin::Scrobble
muzak> songs-by-artist bizmarkie
/home/zolokar/muzak/lib/muzak/index.rb:72:in `songs_by': undefined method `error' for #<Muzak::Index:0x00000002c39248> (NoMethodError)
	from /home/zolokar/muzak/lib/muzak/cmd/index.rb:62:in `songs_by_artist'
	from muzak.rb:41:in `<main>'
```

**Comment by woodruffw** [comment]
Thanks for fixing this in #1.
